import type { Customer, CustomerRepository } from "@/ports/customer-repository";

const customers: Customer[] = [
  {
    id: "cus-001",
    name: "佐藤 美咲",
    kana: "さとう みさき",
    company: "株式会社アトラス",
    role: "マーケティング部 部長",
    email: "misaki.sato@atlas.jp",
    phone: "03-6450-1284",
    location: "東京都 渋谷区",
    status: "active",
    rank: "S",
    lastContactedAt: "2026-09-28",
    registeredAt: "2024-04-12",
    avatarTone: "coral",
    notes: [
      {
        id: "note-001",
        body: "秋季キャンペーンの企画書を送付。来週の定例で予算感をすり合わせる予定。",
        createdAt: "2026-09-28T10:30:00.000Z",
        author: "高橋 健太",
      },
      {
        id: "note-002",
        body: "新サービスに関心あり。導入事例、とくに小売業界の資料を希望。",
        createdAt: "2026-09-15T05:10:00.000Z",
        author: "高橋 健太",
      },
    ],
  },
  {
    id: "cus-002",
    name: "鈴木 健太",
    kana: "すずき けんた",
    company: "ネクストウェーブ合同会社",
    role: "代表社員",
    email: "kenta.suzuki@nextwave.co.jp",
    phone: "090-3128-6674",
    location: "神奈川県 横浜市",
    status: "follow-up",
    rank: "A",
    lastContactedAt: "2026-09-25",
    registeredAt: "2025-01-20",
    avatarTone: "blue",
    notes: [
      {
        id: "note-003",
        body: "無料トライアル終了後の社内稟議について、10月上旬に状況確認する。",
        createdAt: "2026-09-25T01:00:00.000Z",
        author: "高橋 健太",
      },
    ],
  },
  {
    id: "cus-003",
    name: "高橋 彩香",
    kana: "たかはし あやか",
    company: "ミナトデザイン株式会社",
    role: "クリエイティブディレクター",
    email: "ayaka@minato-design.jp",
    phone: "06-6811-9021",
    location: "大阪府 大阪市",
    status: "active",
    rank: "A",
    lastContactedAt: "2026-09-23",
    registeredAt: "2024-08-06",
    avatarTone: "purple",
    notes: [
      {
        id: "note-004",
        body: "ブランドリニューアルに伴うアカウント追加を検討中。見積書を更新する。",
        createdAt: "2026-09-23T08:45:00.000Z",
        author: "高橋 健太",
      },
    ],
  },
  {
    id: "cus-004",
    name: "田中 直樹",
    kana: "たなか なおき",
    company: "株式会社グリーンフィールド",
    role: "事業開発マネージャー",
    email: "n.tanaka@greenfield.jp",
    phone: "052-770-4316",
    location: "愛知県 名古屋市",
    status: "inactive",
    rank: "C",
    lastContactedAt: "2026-08-18",
    registeredAt: "2023-11-15",
    avatarTone: "green",
    notes: [],
  },
  {
    id: "cus-005",
    name: "伊藤 結衣",
    kana: "いとう ゆい",
    company: "リードパートナーズ株式会社",
    role: "執行役員",
    email: "yui.ito@leadpartners.jp",
    phone: "092-410-8820",
    location: "福岡県 福岡市",
    status: "active",
    rank: "S",
    lastContactedAt: "2026-09-19",
    registeredAt: "2025-06-03",
    avatarTone: "amber",
    notes: [
      {
        id: "note-005",
        body: "契約更新の条件を確認。利用人数は次期も現状維持の見込み。",
        createdAt: "2026-09-19T03:20:00.000Z",
        author: "高橋 健太",
      },
    ],
  },
  {
    id: "cus-006",
    name: "山本 大輔",
    kana: "やまもと だいすけ",
    company: "北斗テクノロジー株式会社",
    role: "情報システム部 課長",
    email: "d.yamamoto@hokuto-tech.jp",
    phone: "011-218-5402",
    location: "北海道 札幌市",
    status: "follow-up",
    rank: "B",
    lastContactedAt: "2026-09-12",
    registeredAt: "2025-03-28",
    avatarTone: "blue",
    notes: [],
  },
];

export class InMemoryCustomerRepository implements CustomerRepository {
  async list(): Promise<Customer[]> {
    return structuredClone(customers);
  }
}
